#!/usr/bin/env bash
#SBATCH --job-name=multi_concept_collapse
#SBATCH --output=slurm_multi_concept_%j.log
#SBATCH --time=02:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=40G

source ~/.bashrc
if [ -f ~/miniconda/etc/profile.d/conda.sh ]; then
    source ~/miniconda/etc/profile.d/conda.sh
elif [ -f ~/miniconda3/etc/profile.d/conda.sh ]; then
    source ~/miniconda3/etc/profile.d/conda.sh
fi
conda activate speed_env || conda activate mace_env

cd $SLURM_SUBMIT_DIR

# Verify single-concept Van Gogh checkpoint exists (generated by prior experiment)
if [ ! -f "checkpoints/speed/few-concept/style/Van Gogh.pt" ]; then
    echo "ERROR: Van Gogh checkpoint missing. Run setup_speed.sh first."
    exit 1
fi

mkdir -p checkpoints/speed/multi/2concept
mkdir -p checkpoints/speed/multi/3concept

# ================================================================
# Step 1: Generate multi-concept SPEED checkpoints
# SPEED is training-free — each takes ~60 seconds
# ================================================================

echo "=== Building 2-concept checkpoint: Van Gogh + Picasso ==="
cd SPEED_repo
python train_erase_null.py \
    --baseline SPEED \
    --target_concepts "Van Gogh, Picasso" \
    --anchor_concepts "art" \
    --retain_path "data/style.csv" --heads "concept" \
    --save_path "../checkpoints/speed/multi/2concept" \
    --file_name "weight" \
    --params V --aug_num 10 --threshold 1e-1
cd ..

echo "=== Building 3-concept checkpoint: Van Gogh + Picasso + Monet ==="
cd SPEED_repo
python train_erase_null.py \
    --baseline SPEED \
    --target_concepts "Van Gogh, Picasso, Monet" \
    --anchor_concepts "art" \
    --retain_path "data/style.csv" --heads "concept" \
    --save_path "../checkpoints/speed/multi/3concept" \
    --file_name "weight" \
    --params V --aug_num 10 --threshold 1e-1
cd ..

# ================================================================
# Step 2: Generate images for all test artists, all 4 methods
# ================================================================

echo "=== Generating: Baseline ==="
python experiment3/scripts/probe_multi_concept.py \
    --method baseline \
    --out_dir experiment3/results/multi_concept

echo "=== Generating: SPEED 1-concept (Van Gogh only) ==="
python experiment3/scripts/probe_multi_concept.py \
    --method speed_1c \
    --ckpt "checkpoints/speed/few-concept/style/Van Gogh.pt" \
    --out_dir experiment3/results/multi_concept

echo "=== Generating: SPEED 2-concept (Van Gogh + Picasso) ==="
python experiment3/scripts/probe_multi_concept.py \
    --method speed_2c \
    --ckpt "checkpoints/speed/multi/2concept/weight.pt" \
    --out_dir experiment3/results/multi_concept

echo "=== Generating: SPEED 3-concept (Van Gogh + Picasso + Monet) ==="
python experiment3/scripts/probe_multi_concept.py \
    --method speed_3c \
    --ckpt "checkpoints/speed/multi/3concept/weight.pt" \
    --out_dir experiment3/results/multi_concept

echo "=== All multi-concept probes complete. ==="
echo "Results in experiment3/results/multi_concept/"
echo "Commit with: git add experiment3/results/multi_concept/ && git commit -m 'Add multi-concept collapse results'"
